Add new cypress command to add IAP headers w/o a cy.visit.
onXmaps/cypress-iap pull request #47
Opened 2022-03-29 18:22 UTC by kirkchambers-onx

Basically a carbon copy of the overwritten command.
Adds the index.d.ts so I can export this command and not let vscode complain.

Full disclosure: Adding a new cypress command in a submodule is fresh territory for me, so I'm sure I did something dumb here.
This is just a stab at getting us unblocked.

# Open Questions:
- Do I need to update `package-lock.json`? I only did `package.json`
- Should I clean up this code and find a way to reuse stuff between `visit.js` and the new `manualAddIAPHeader.js`?
- Does this PR make me look fat?

# Testing comments:
- I manually inserted these changes into `/node-modules` in the webmap repo.
Would "be nice" to actually test pulling this, but I'm not smart enough to setup a specific branch like that as an npm depencency.

2022-03-30 17:19 UTC, beccagsc approved these changes

2022-03-30 20:18 UTC, coltdorsey commented
What if tried tapping in to the `on:before:load` or `on:load` event in `support/plugins.js` file? Maybe something like:
The idea here is that we've found there are situations where we want the header to be applied outside of cy.visit calls.

```
Cypress.on('window:before:load', (win) => {
//Cypress.on('window:load', (win) => {
  if (Cypress.config().baseUrl.indexOf("localhost") != -1) {
        return
    } else {
        cy.exec(
            `curl -I ${Cypress.config().baseUrl
            } | awk '/^location/ {split($NF, a, /[=&]/); print a[2]}'`
        )
            .then((client_id) => {
                return client_id.stdout;
            })
            .then((client_id) => {
                cy.task("getIAPToken", {
                    url: Cypress.config().baseUrl,
                    cid: client_id,
                }).then((iapToken) => {
                    cy.intercept(`${Cypress.config().baseUrl}/**`, (req) => {
                        req.headers["Proxy-Authorization"] = `${iapToken}`;
                    })
                })
            })
    }
})
```

2022-03-30 20:27 UTC, coltdorsey commented
> Do I need to update package-lock.json? I only did package.json

I personally run `npm ci` after I make any changes in a `package.json` so that it syncs the `package-lock.json`

> Should I clean up this code and find a way to reuse stuff between visit.js and the new manualAddIAPHeader.js?

See thoughts @ https://github.com/onXmaps/cypress-iap/pull/47#issuecomment-1083584282

> Does this PR make me look fat?

🤣 ..... Not as a whole, just the `index.d.ts` file.

2022-03-30 23:00 UTC, onxrob commented
> What if tried tapping in to the `on:before:load` or `on:load` event in `support/plugins.js` file? Maybe something like: The idea here is that we've found there are situations where we want the header to be applied outside of cy.visit calls.
> 
> ```
> Cypress.on('window:before:load', (win) => {
> //Cypress.on('window:load', (win) => {
>   if (Cypress.config().baseUrl.indexOf("localhost") != -1) {
>         return
>     } else {
>         cy.exec(
>             `curl -I ${Cypress.config().baseUrl
>             } | awk '/^location/ {split($NF, a, /[=&]/); print a[2]}'`
>         )
>             .then((client_id) => {
>                 return client_id.stdout;
>             })
>             .then((client_id) => {
>                 cy.task("getIAPToken", {
>                     url: Cypress.config().baseUrl,
>                     cid: client_id,
>                 }).then((iapToken) => {
>                     cy.intercept(`${Cypress.config().baseUrl}/**`, (req) => {
>                         req.headers["Proxy-Authorization"] = `${iapToken}`;
>                     })
>                 })
>             })
>     }
> })
> ```

Yes, this would be a good path to explore. One other case not captured by overriding cy.visit() is cy.reload()

2022-04-12 16:08 UTC, onxrob requested changes
* We can remove "manual" from the new function name
* I agree with Kirk's suggestion to refactor to avoid code duplication between the new command and the overridden `visit` command.
* We should also add documentation in README.md when and how to use the new function, since it might not be obvious.
* Is there any practical way to add unit tests since this is an open-sourced component?

2022-04-12 16:15 UTC, beccagsc commented
We don't need this functionality as this time- closing with Kirk's blessing.

2022-04-12 16:15 UTC, closed without merging